files: '^script|tests|pytest_containers'
repos:
  - repo: meta
    hooks:
      - id: identity
        types: [python]
  - repo: https://github.com/ambv/black
    rev: c160e4b7ce30c661ac4f2dfa5038becf1b8c5c33
    hooks:
      - id: black
        args: [--safe, --quiet, --line-length=120]
        language_version: python3.9
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 61b5f7e6f73c8308fc77c9fcfd10005ab7d14b80
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-builtin-literals
      - id: check-json
      - id: check-merge-conflict
      - id: forbid-submodules
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 32119baf69e913a72f2e1b1fbe0d56921b670ebb
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [--non-interactive, --install-types]
  - repo: https://github.com/PyCQA/flake8
    rev: 564dc51f72611eeb96507df077786b149072a07e
    hooks:
      - id: flake8
        args: [--max-line-length=120]
  - repo: https://github.com/symonk/pre-commit-pdb-vars
    rev: 0.5.0
    hooks:
      - id: pdb-vars
        args: [--ignore, commands]
  - repo: https://github.com/hadialqattan/pycln
    rev: a965b2d45e2007bfa2484ebb015eaa2ee0c1a75e
    hooks:
      - id: pycln
        args: [--config=pyproject.toml, --all]
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [-i, --wrap-summaries, "120", --wrap-descriptions, "120"]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: b8038ee58e2c6a5ad14a384f41c5451430a6854e
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]