site_name: pytest_containers 
site_description: A pytest plugin for running docker containers as part of integration tests 
site_url:
theme:
  name: material
  features:
    - content.code.annotate
  palette:
    primary: light blue
    accent: purple
  font:
    text: Work Sans
    code: Work Sans
  icon:
    repo: fontawesome/brands/git
repo_name: symonk/pytest-containers
repo_url: https://github.com/symonk/pytest-containers/
edit_uri: ""

nav:
    - Introduction: index.md
    - QuickStart: quickstart.md 
    - Advanced Usage: advanced.md
plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            selection:
              docstring_style: sphinx
            rendering:
              line_length: 88
              show_if_no_docstring: false
              merge_init_into_class: true
              show_source: false
              docstring_section_style: table
        watch:
          - pytest_containers/
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
copyright: Copyright &copy Simon Kerr