[tool.poetry]
name = "pytest-containers"
version = "0.1.0"
description = "A pytest plugin for starting docker compose services around tests"
authors = ["symonk <jackofspaces@gmail.com>"]
license = "Apache License 2.0"
readme = "README.md"
packages = [{include = "pytest_containers"}]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.2.2"
docker = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
